name: Publish to GitHub Packages

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      
      - name: Build package
        run: python -m build
      
      - name: Publish to GitHub Packages
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://github.com/${{ github.repository }}/packages
          password: ${{ secrets.GITHUB_TOKEN }}
          skip-existing: true 